export const FETCH_CART_ITEMS_REQUEST = "FETCH_CART_ITEMS_REQUEST";
export const FETCH_CART_ITEMS_SUCCESS = "FETCH_CART_ITEMS_SUCCESS";
export const FETCH_CART_ITEMS_FAIL = "FETCH_CART_ITEMS_FAIL";

export const ADD_ITEM_TO_CART_REQUEST = "ADD_ITEM_TO_CART_REQUEST";
export const ADD_ITEM_TO_CART_SUCCESS = "ADD_ITEM_TO_CART_SUCCESS";
export const ADD_ITEM_TO_CART_FAIL = "ADD_ITEM_TO_CART_FAIL";

export const REMOVE_ITEM_FROM_CART_REQUEST = "REMOVE_ITEM_FROM_CART_REQUEST";
export const REMOVE_ITEM_FROM_CART_SUCCESS = "REMOVE_ITEM_FROM_CART_SUCCESS";
export const REMOVE_ITEM_FROM_CART_FAIL = "REMOVE_ITEM_FROM_CART_FAIL";

export const DELETE_ITEM_FROM_CART_REQUEST = "DELETE_ITEM_FROM_CART_REQUEST";
export const DELETE_ITEM_FROM_CART_SUCCESS = "DELETE_ITEM_FROM_CART_SUCCESS";
export const DELETE_ITEM_FROM_CART_FAIL = "DELETE_ITEM_FROM_CART_FAIL";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const RESET_CART_ITEM = "RESET_CART_ITEM";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
