export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const LOAD_CURRENTUSER_REQUEST = "LOAD_CURRENTUSER_REQUEST";
export const LOAD_CURRENTUSER_SUCCESS = "LOAD_CURRENTUSER_SUCCESS";
export const LOAD_CURRENTUSER_FAIL = "LOAD_CURRENTUSER_FAIL";

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const UPATE_USER_PROFILE_REQUEST = "UPATE_USER_PROFILE_REQUEST";
export const UPATE_USER_PROFILE_SUCCESS = "UPATE_USER_PROFILE_SUCCESS";
export const RESET_USER_UPDATE_PROFILE = "RESET_USER_UPDATE_PROFILE";
export const UPATE_USER_PROFILE_FAIL = "UPATE_USER_PROFILE_FAIL";

export const UPATED_USER_PASSWORD_REQUEST = "UPATED_USER_PASSWORD_REQUEST";
export const UPATED_USER_PASSWORD_SUCCESS = "UPATED_USER_PASSWORD_SUCCESS";
export const UPATED_USER_PASSWORD_FAIL = "UPATED_USER_PASSWORD_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const FORGOT_USER_PASSWORD_REQUEST = "FORGOT_USER_PASSWORD_REQUEST";
export const FORGOT_USER_PASSWORD_SUCCESS = "FORGOT_USER_PASSWORD_SUCCESS";
export const FORGOT_USER_PASSWORD_FAIL = "FORGOT_USER_PASSWORD_FAIL";

export const RESET_USER_PASSWORD_REQUEST = "RESET_USER_PASSWORD_REQUEST";
export const RESET_USER_PASSWORD_SUCCESS = "RESET_USER_PASSWORD_SUCCESS";
export const RESET_USER_PASSWORD_FAIL = "RESET_USER_PASSWORD_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
